/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2022-04-28 13:57:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addmember_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<!-- \r\n");
      out.write("<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    function checkPw() {\r\n");
      out.write("    \tlet name = $(\"#name\").val();\r\n");
      out.write("    \tlet write = $(\"#write\").val();\r\n");
      out.write("        let id = $(\"#id\").val();\r\n");
      out.write("        let pw = $(\"#password\").val();\r\n");
      out.write("        let number = pw.search(/[0-9]/g);\r\n");
      out.write("        let english = pw.search(/[a-z]/ig);\r\n");
      out.write("        let spece = pw.search(/[`~!@@#$%^&*|₩₩₩'₩\";:₩/?]/gi);\r\n");
      out.write("        let reg = /^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$/;\r\n");
      out.write("        if (name ==\"\"){\r\n");
      out.write("     \t   alert('이름을 입력하세요 ');\r\n");
      out.write("        };\r\n");
      out.write("        \r\n");
      out.write("        if (write == \"\"){\r\n");
      out.write("      \t   alert('글내용을 입력하세요');\r\n");
      out.write("         };\r\n");
      out.write("         \r\n");
      out.write("        if (pw.length < 8 || pw.length > 20) {\r\n");
      out.write("            alert(\"8자리 ~ 20자리 이내로 입력해주세요.\");\r\n");
      out.write("            return false;\r\n");
      out.write("\r\n");
      out.write("        } else if (pw.search(/\\s/) != -1) {\r\n");
      out.write("            alert(\"비밀번호는 공백 없이 입력해주세요.\");\r\n");
      out.write("            return false;\r\n");
      out.write("\r\n");
      out.write("        } else if (number < 0 || english < 0 || spece < 0) {\r\n");
      out.write("            alert(\"영문,숫자,특수문자를 혼합하여 입력해주세요.\");\r\n");
      out.write("            return false;\r\n");
      out.write("\r\n");
      out.write("        } else if ((number < 0 && english < 0) || (english < 0 && spece < 0) || (spece < 0 && number < 0)) {\r\n");
      out.write("            alert(\"영문,숫자, 특수문자 중 2가지 이상을 혼합하여 입력해주세요.\");\r\n");
      out.write("            return false;\r\n");
      out.write("\r\n");
      out.write("        } else if (/(\\w)\\1\\1\\1/.test(pw)) {\r\n");
      out.write("            alert('같은 문자를 4번 이상 사용하실 수 없습니다.');\r\n");
      out.write("            return false;\r\n");
      out.write("\r\n");
      out.write("        } else if (pw.search(id) > -1) {\r\n");
      out.write("            alert(\"비밀번호에 아이디가 포함되었습니다.\");\r\n");
      out.write("            return false;\r\n");
      out.write("        } else {\r\n");
      out.write("            alert(\"비밀번호가 정상적으로 입력되었습니다.\");\r\n");
      out.write("            return true;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        if (false === reg.test(pw)) {\r\n");
      out.write("            alert('비밀번호는 8자 이상이어야 하며, 숫자/대문자/소문자/특수문자를 모두 포함해야 합니다.');\r\n");
      out.write("            return false;\r\n");
      out.write("        } else {\r\n");
      out.write("            alert(\"비밀번호가 정상적으로 입력되었습니다.\");\r\n");
      out.write("            return true;\r\n");
      out.write("        }\r\n");
      out.write("   \r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write(" -->\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>글쓰기</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<form action=\"addmember.do\" method=\"POST\" id=\"addmemberform\" onsubmit=\"\">\r\n");
      out.write("\t<input type=\"button\" style=\"float: right;\" size=\"10%\" value=\"뒤로가기\" onclick=\"document.location.href='listmember.do'\">\r\n");
      out.write("\r\n");
      out.write("\t\t<center>글쓰기</center>\r\n");
      out.write("\t\t<table border=\"1\" align=\"center\" style=\"background-color: ivory;\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>이름:<input type=\"text\" id=\"name\" name=\"name\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>비밀번호:<input type=\"text\" id=\"password\" name=\"password\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><textarea style=\"width=100%;\" size=\"100%;\" name=\"write\" id=\"text\" style=\"resize: none;\">\r\n");
      out.write("\t\t\t\t</textarea></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr align=\"center\">\r\n");
      out.write("\t\t\t\t<td> <button onclick=\"checkPw()\">확인</button>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<input type=\"reset\" value=\"취소\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"뒤로가기\" onclick=\"document.location.href='listmember.do'\">\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
